name: Salesforce Code Quality

on:
    workflow_dispatch:
    workflow_call:

jobs:
    PMD:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-node@v3
          - name: Setup Salesforce CLI
            run: |
                yarn global add @salesforce/cli
                sf plugins:install @salesforce/sfdx-scanner
          - name: SF Code Analyzer - PMD - Report findings as comments
            uses: mitchspano/sfdx-scan-pull-request@v0.1.16
            with:
              report-mode: comments
              engine: pmd
              pmdconfig: config/pmd/ruleset.xml
              severity-threshold: 4
              strictly-enforced-rules: '[{ "engine": "pmd", "category": "Performance", "rule": "AvoidDebugStatements" }]'
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    RetireJS:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v3
            - name: Setup Salesforce CLI
              run: |
                  yarn global add @salesforce/cli
                  sf plugins:install @salesforce/sfdx-scanner
            - name: SF Code Analyzer - RetireJS - Report findings as comments
              uses: mitchspano/sfdx-scan-pull-request@v0.1.16
              with:
                report-mode: comments
                engine: retire-js
                severity-threshold: 4
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    ESLint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v3
            - name: Setup Salesforce CLI
              run: |
                  yarn global add @salesforce/cli
                  sf plugins:install @salesforce/sfdx-scanner
            - name: Install deps
              run: |
                  yarn install
            - name: SF Code Analyzer - ESLint - Report findings as comments
              uses: mitchspano/sfdx-scan-pull-request@v0.1.16
              with:
                report-mode: comments
                engine: eslint
                eslintconfig: .eslintrc.json
                severity-threshold: 4
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    GraphEngine:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v3
            - name: Setup Salesforce CLI
              run: |
                  yarn global add @salesforce/cli
                  sf plugins:install @salesforce/sfdx-scanner
            - name: SF Code Analyzer - Data Flow Analysis
              run: |
                  sf scanner:run:dfa --target force-app --projectdir force-app --format table --severity-threshold 3
